In [142]:
import pandas as pd
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

# Your code here
# ...

In [5]:
peregrinos = pd.read_csv('peres_futu.csv')

In [6]:
peregrinos['Fecha'] = pd.to_datetime(peregrinos['Fecha'], format='%d/%m/%Y')

peregrinos = peregrinos.set_index('Fecha')
peregrinos.index = pd.to_datetime(peregrinos.index)

In [16]:
def add_time_features(df):
    df = df.copy()
  
    df['dayofyear'] = df.index.dayofyear

    return df

In [17]:
add_time_features(peregrinos)

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear
Fecha,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000003,44746,2.0,Cruz de Ferro,NaN,NaN,NaN,185
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
...,...,...,...,...,...,...,...,...
2022-07-10,P012934,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012935,44752,0.0,Monforte de Lemos,NaN,NaN,NaN,191
2022-07-10,P012936,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012937,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012938,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191

In [ ]:
dict

In [70]:
peregrinos_4dejulio = peregrinos[peregrinos.index< '2022-07-05'].Codigo.tolist()

In [19]:
peregrinos_fran = peregrinos[peregrinos['Camino'] =='Frances']

In [20]:
etaps = pd.read_excel('Caminos con etapas 2.xlsx', header= 2)
etaps = etaps.rename(columns={'Ciudad': 'Origen'})


etaps.head(2)

    Camino  Etapa                  Origen    km
0  Frances      0  Santiago de Compostela   0.0
1  Frances      1             O Pedrouzo   19.4

In [21]:
etapas_f =etaps[ etaps['Camino']=='Frances']
etapas_f = etapas_f['Origen']

In [22]:
etapas_f[0:8]

0    Santiago de Compostela
1               O Pedrouzo
2                    Arzúa
3             Palas de Rei
4               Portomarín
5                   Sarria
6              Triacastela
7               O Cebreiro
Name: Origen, dtype: object

In [23]:
lista = ['-']
lista = lista*6028

In [24]:
peregrinos_fran = add_time_features(peregrinos_fran)
peregrinos_fran.head()

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear
Fecha,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000006,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185

In [25]:

df_itinerario =pd.DataFrame()

df_itinerario['Peregrino'] = peregrinos_fran['Codigo']

df_itinerario.reset_index(inplace=True)
df_itinerario.drop(columns='Fecha', inplace=True)
df_itinerario

     Peregrino
0      P000001
1      P000002
2      P000004
3      P000005
4      P000006
...        ...
6023   P012933
6024   P012934
6025   P012936
6026   P012937
6027   P012938

[6028 rows x 1 columns]

In [26]:
for i in range(6028):
    
    llegada = peregrinos_fran.iloc[i,7]
    etapa = peregrinos_fran.iloc[i,6]
    etapa = int(etapa)
    
    for e in range(etapa):
        df_itinerario.loc[i,llegada-e] = etapas_f[e+1]

In [27]:
df_itinerario

,Peregrino,185,184,183,182,181,180,179,178,177,...,156,155,154,153,186,187,188,189,190,191
0,P000001,O Pedrouzo,Arzúa,Palas de Rei,Portomarín,Sarria,Triacastela,O Cebreiro,Villafranca Del Bierzo,Ponferrada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P000002,O Pedrouzo,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P000004,O Pedrouzo,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P000005,O Pedrouzo,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P000006,O Pedrouzo,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6023,P012933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,O Pedrouzo
6024,P012934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,O Pedrouzo
6025,P012936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,O Pedrouzo
6026,P012937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,O Pedrouzo
6027,P012938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,O Pedrouzo

In [28]:
peregrinos.Camino.unique()

array(['Frances', nan, 'Portugues', 'Norte', 'SanabrÃ©s', 'Ingles',
       'Primitivo', 'PortuguÃ©s por la costa'], dtype=object)

In [29]:
peregrinos.Camino = peregrinos.Camino.astype(str)

In [30]:
peregrinos['Camino'] = [s.replace("PortuguÃ©s por la costa" , "Portugues por la costa") for s in peregrinos.Camino]  

peregrinos['Camino'] = [s.replace("SanabrÃ©s" , "Sanabres") for s in peregrinos.Camino]  

peregrinos.Camino.unique()

array(['Frances', 'nan', 'Portugues', 'Norte', 'Sanabres', 'Ingles',
       'Primitivo', 'Portugues por la costa'], dtype=object)

In [31]:
etaps['Camino'] = [s.replace("Portugués por la costa" , "Costa") for s in etaps.Camino]

In [32]:
nombres_caminos = etaps.Camino.unique().tolist()

In [33]:
lista_nombres =[]
for caminos in nombres_caminos:
    lista_nombres.append(caminos)

In [34]:
for l,caminos in zip(lista_nombres,nombres_caminos):
    aux =etaps[ etaps['Camino']== caminos]
    locals()[l] = aux['Origen']

In [35]:
Sanabres= Sanabrés

In [36]:
Frances

0             Santiago de Compostela
1                        O Pedrouzo
2                             Arzúa
3                      Palas de Rei
4                        Portomarín
5                            Sarria
6                       Triacastela
7                        O Cebreiro
8            Villafranca Del Bierzo
9                        Ponferrada
10                       Foncebadón
11                          Astorga
12            San Martín Del Camino
13                             León
14            Mansilla De Las Mulas
15        Bercianos Del Real Camino
16    Terradillos De Los Templarios
17            Carrión De Los Condes
18                         Frómista
19                      Castrojeriz
20             Hornillos Del Camino
21                           Burgos
22               San Juan De Ortega
23                         Belorado
24      Santo Domingo de La Calzada
25                           Nájera
26                           Logroño
27                        Los Arcos
28                          Estella
29                  Puente la Reina
30                         Pamplona
31                           Zubiri
32                     Roncesvalles
33          Saint Jean Pied de Port
Name: Origen, dtype: object

In [37]:
Ingles

34    Santiago de Compostela
35                 Sigüeiro
36                    Bruma
37                 Betanzos
38               Pontedeume
39                     Neda
40                   Ferrol
Name: Origen, dtype: object

In [39]:
Norte

41    Santiago de Compostela
42               O Pedrouzo
43                    Arzúa
44       Sobrado dos Monxes
45                 Baamonde
46                  Vilalba
47                   Abadín
48                 Lourenzá
49                  Ribadeo
50               La Caridad
51                   Luarca
52                 Cadavedo
53            Soto de Luiña
54           Muros de Nalón
55                   Avilés
56                    Gijón
57                  Sebrayo
58              Ribadesella
59                   Llanes
60                Colombres
61                 Comillas
62       Santillana del Mar
63                Santander
64                   Güemes
65                   Laredo
66          Castro Urdiales
67              Portugalete
68                   Bilbao
69                   Lezama
70             Gernika Lumo
71                   Markina
72                     Deba
73                  Zarautz
74            San Sebastián
75                     Irún
Name: Origen, dtype: object

In [40]:
peregrinos = add_time_features(peregrinos)
peregrinos.head()

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear
Fecha,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000003,44746,2.0,Cruz de Ferro,nan,NaN,NaN,185
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185

In [41]:
peregrinos_ = peregrinos[peregrinos.Etapa.notna()]
peregrinos_

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear
Fecha,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
2022-07-04,P000006,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185
...,...,...,...,...,...,...,...,...
2022-07-10,P012933,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012934,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012936,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012937,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191
2022-07-10,P012938,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191

In [42]:

df_itinerario =pd.DataFrame()

df_itinerario['Peregrino'] = peregrinos_['Codigo']

df_itinerario.reset_index(inplace=True)
df_itinerario.drop(columns='Fecha', inplace=True)

In [43]:
Portugues.iloc[0]

'Santiago de Compostela'

In [44]:
peregrinos_[peregrinos_.Camino == 'Portugues']

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear
Fecha,,,,,,,,
2022-07-04,P003691,44746,1.0,ValenÃ§a do Minho,Portugues,ValenÃ§a do MinhoPortugues,6.0,185
2022-07-04,P003692,44746,1.0,Tui,Portugues,TuiPortugues,6.0,185
2022-07-04,P003694,44746,1.0,Tui,Portugues,TuiPortugues,6.0,185
2022-07-04,P003697,44746,1.0,Tui,Portugues,TuiPortugues,6.0,185
2022-07-04,P003698,44746,1.0,Lisboa,Portugues,LisboaPortugues,25.0,185
...,...,...,...,...,...,...,...,...
2022-07-10,P009003,44752,1.0,Tui,Portugues,TuiPortugues,6.0,191
2022-07-10,P009007,44752,1.0,Tui,Portugues,TuiPortugues,6.0,191
2022-07-10,P009009,44752,1.0,Tui,Portugues,TuiPortugues,6.0,191
2022-07-10,P009012,44752,1.0,Tui,Portugues,TuiPortugues,6.0,191
2022-07-10,P009013,44752,1.0,Tui,Portugues,TuiPortugues,6.0,191

In [45]:
peregrinos_['llegada'] = peregrinos_.dayofyear - 152

/var/folders/rv/z0yvw1vn57j7rg7v3j11b_3r0000gn/T/ipykernel_31149/443314824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peregrinos_['llegada'] = peregrinos_.dayofyear - 152

In [46]:
peregrinos_

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear,llegada
Fecha,,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185,33
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000006,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
...,...,...,...,...,...,...,...,...,...
2022-07-10,P012933,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012934,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012936,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012937,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012938,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39

In [61]:

df_itinerario =pd.DataFrame()

df_itinerario['Peregrino'] = peregrinos_['Codigo']

df_itinerario.reset_index(inplace=True)
df_itinerario.drop(columns='Fecha', inplace=True)

In [62]:
for i in range(len(peregrinos_)):
    
    llegada = peregrinos_.iloc[i,7]
    etapa = peregrinos_.iloc[i,6]
    etapa = int(etapa)
    
    for e in range(etapa):
        camino = peregrinos_.iloc[i,4]
        if (camino =='Portugues por la costa'):
            camino = 'Costa'
        df_itinerario.loc[i,str(llegada)] = Frances.iloc[0]


        if e+1< len(locals()[camino]):
            df_itinerario.loc[i,str(llegada-e)] = locals()[camino].iloc[e+1]

In [63]:
df_itinerario.head(5)

,Peregrino,185,184,183,182,181,180,179,178,177,...,155,154,153,186,187,188,189,190,191,152
0,P000001,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,Triacastela,O Cebreiro,Villafranca Del Bierzo,Ponferrada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P000002,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P000004,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P000005,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P000006,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df_itinerario_sorted = df_itinerario.reindex(sorted(df_itinerario.columns), axis=1)

In [65]:
df_itinerario_sorted.set_index('Peregrino', inplace=True)

In [66]:

# Obtener el índice de las columnas que representan días del año
dias_del_anio = [int(col) for col in df_itinerario_sorted.columns[1:]]


# Convertir los números en objetos de fecha y aplicar el formato deseado
nombres_columnas_nuevos = [pd.to_datetime('2022-12-31') + pd.DateOffset(days=dia) for dia in dias_del_anio]
nombres_columnas_nuevos = [fecha.strftime('%d/%m/%Y') for fecha in nombres_columnas_nuevos]

# Asignar los nuevos nombres de columna al DataFrame
df_itinerario_sorted.columns = df_itinerario_sorted.columns[:1].tolist() + nombres_columnas_nuevos

print(df_itinerario_sorted)

           152 02/06/2023 03/06/2023 04/06/2023 05/06/2023 06/06/2023  \
Peregrino
P000001    NaN        NaN        NaN        NaN        NaN        NaN
P000002    NaN        NaN        NaN        NaN        NaN        NaN
P000004    NaN        NaN        NaN        NaN        NaN        NaN
P000005    NaN        NaN        NaN        NaN        NaN        NaN
P000006    NaN        NaN        NaN        NaN        NaN        NaN
...        ...        ...        ...        ...        ...        ...
P012933    NaN        NaN        NaN        NaN        NaN        NaN
P012934    NaN        NaN        NaN        NaN        NaN        NaN
P012936    NaN        NaN        NaN        NaN        NaN        NaN
P012937    NaN        NaN        NaN        NaN        NaN        NaN
P012938    NaN        NaN        NaN        NaN        NaN        NaN

          07/06/2023 08/06/2023 09/06/2023 10/06/2023  ...   01/07/2023  \
Peregrino                                              ...
P000001          NaN        NaN        NaN        NaN  ...  Portomarín
P000002          NaN        NaN        NaN        NaN  ...  Portomarín
P000004          NaN        NaN        NaN        NaN  ...  Portomarín
P000005          NaN        NaN        NaN        NaN  ...  Portomarín
P000006          NaN        NaN        NaN        NaN  ...  Portomarín
...              ...        ...        ...        ...  ...          ...
P012933          NaN        NaN        NaN        NaN  ...          NaN
P012934          NaN        NaN        NaN        NaN  ...          NaN
P012936          NaN        NaN        NaN        NaN  ...          NaN
P012937          NaN        NaN        NaN        NaN  ...          NaN
P012938          NaN        NaN        NaN        NaN  ...          NaN

              02/07/2023 03/07/2023              04/07/2023 05/07/2023  \
Peregrino
P000001    Palas de Rei      Arzúa   Santiago de Compostela        NaN
P000002    Palas de Rei      Arzúa   Santiago de Compostela        NaN
P000004    Palas de Rei      Arzúa   Santiago de Compostela        NaN
P000005    Palas de Rei      Arzúa   Santiago de Compostela        NaN
P000006    Palas de Rei      Arzúa   Santiago de Compostela        NaN
...                  ...        ...                     ...        ...
P012933              NaN        NaN                     NaN        NaN
P012934              NaN        NaN                     NaN        NaN
P012936              NaN        NaN                     NaN        NaN
P012937              NaN        NaN                     NaN        NaN
P012938              NaN        NaN                     NaN        NaN

          06/07/2023   07/07/2023     08/07/2023 09/07/2023  \
Peregrino
P000001          NaN          NaN            NaN        NaN
P000002          NaN          NaN            NaN        NaN
P000004          NaN          NaN            NaN        NaN
P000005          NaN          NaN            NaN        NaN
P000006          NaN          NaN            NaN        NaN
...              ...          ...            ...        ...
P012933      Sarria   Portomarín   Palas de Rei      Arzúa
P012934      Sarria   Portomarín   Palas de Rei      Arzúa
P012936      Sarria   Portomarín   Palas de Rei      Arzúa
P012937      Sarria   Portomarín   Palas de Rei      Arzúa
P012938      Sarria   Portomarín   Palas de Rei      Arzúa

                       10/07/2023
Peregrino
P000001                       NaN
P000002                       NaN
P000004                       NaN
P000005                       NaN
P000006                       NaN
...                           ...
P012933    Santiago de Compostela
P012934    Santiago de Compostela
P012936    Santiago de Compostela
P012937    Santiago de Compostela
P012938    Santiago de Compostela

[11216 rows x 40 columns]

In [67]:
df_itinerario_sorted.to_csv('itinerario_s.csv')

In [68]:
df_itinerario_sorted

,152,02/06/2023,03/06/2023,04/06/2023,05/06/2023,06/06/2023,07/06/2023,08/06/2023,09/06/2023,10/06/2023,...,01/07/2023,02/07/2023,03/07/2023,04/07/2023,05/07/2023,06/07/2023,07/07/2023,08/07/2023,09/07/2023,10/07/2023
Peregrino,,,,,,,,,,,,,,,,,,,,,
P000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P012933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela
P012934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela
P012936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela
P012937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela
P012938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela

In [69]:
df_itinerario_sorted[df_itinerario_sorted['04/07/2023'] == 'Santiago de Compostela']

,152,02/06/2023,03/06/2023,04/06/2023,05/06/2023,06/06/2023,07/06/2023,08/06/2023,09/06/2023,10/06/2023,...,01/07/2023,02/07/2023,03/07/2023,04/07/2023,05/07/2023,06/07/2023,07/07/2023,08/07/2023,09/07/2023,10/07/2023
Peregrino,,,,,,,,,,,,,,,,,,,,,
P000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P009432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P009433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P009434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P009435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN
P009437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ourense,Cea,A Laxe,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
pere_itinerario_4julio = df_itinerario_sorted[df_itinerario_sorted['04/07/2023'] == 'Santiago de Compostela'].index.tolist()

In [73]:
for pere in peregrinos_4dejulio:
    if pere in pere_itinerario_4julio:
        pass
    else :
        print(pere)

P000003
P000009
P000012
P000050
P000052
P000059
P000060
P000077
P000098
P000103
P000105
P000106
P000120
P000132
P000147
P000148
P000160
P000192
P000201
P000219
P000220
P000228
P000251
P000258
P000259
P000280
P000316
P000325
P000327
P000341
P000343
P000345
P000355
P000358
P000377
P000384
P000393
P000401
P003707
P003714
P003722
P003725
P003726
P003749
P003764
P003767
P003787
P003795
P003800
P003803
P003809
P003815
P003816
P003821
P003822
P003825
P003828
P003834
P003837
P003841
P003847
P003856
P003868
P003875
P003878
P003882
P003884
P003887
P003890
P003892
P003893
P003894
P003902
P003904
P003906
P003909
P003911
P003916
P003924
P003930
P003943
P003951
P003955
P003963
P003972
P003987
P003994
P004003
P004005
P004006
P004012
P004015
P004024
P004030
P004031
P004033
P004041
P004055
P004064
P004078
P004089
P004091
P004098
P004102
P004105
P004106
P004109
P004121
P004122
P004132
P004150
P004153
P004158
P004161
P004170
P004173
P004189
P004190
P004193
P004195
P004197
P004201
P004208
P004209
P004221
P004222
P004226
P004229
P004230
P004245
P004254
P004257
P004259
P004266
P009022
P009025
P009032
P009040
P009047
P009060
P009062
P009083
P009104
P009111
P009115
P009117
P009121
P009122
P009143
P009146
P009159
P009172
P009185
P009192
P009194
P009200
P009206
P009214
P009220
P009224
P009225
P009230
P009231
P009242
P009251
P009262
P009264
P009274
P009287
P009300
P009303
P009314
P009315
P009316
P009324
P009356
P009358
P009370
P009374
P009394
P009400
P009406
P009412
P009416
P009423
P009436

In [74]:
len(peregrinos_4dejulio)

1411

In [75]:
len(pere_itinerario_4julio)

1225

In [80]:
peregrinos[peregrinos.index< '2022-07-05'].Etapa.isna().value_counts()

False    1225
True      186
Name: Etapa, dtype: int64

In [3]:
df_itinerario_sorted = pd.read_csv('itinerario_s.csv')

In [15]:
df_itinerario_sorted[df_itinerario_sorted['04/07/2023'] == 'Santiago de Compostela']

Empty DataFrame
Columns: [Peregrino, 152, 03/06/2023, 04/06/2023, 05/06/2023, 06/06/2023, 07/06/2023, 08/06/2023, 09/06/2023, 10/06/2023, 11/06/2023, 12/06/2023, 13/06/2023, 14/06/2023, 15/06/2023, 16/06/2023, 17/06/2023, 18/06/2023, 19/06/2023, 20/06/2023, 21/06/2023, 22/06/2023, 23/06/2023, 24/06/2023, 25/06/2023, 26/06/2023, 27/06/2023, 28/06/2023, 29/06/2023, 30/06/2023, 01/07/2023, 02/07/2023, 03/07/2023, 04/07/2023, 05/07/2023, 06/07/2023, 07/07/2023, 08/07/2023, 09/07/2023, 10/07/2023, 11/07/2023]
Index: []

[0 rows x 41 columns]

In [90]:
df_itinerario_sorted['23/06/2023'].value_counts()

Terradillos De Los Templarios     77
León                              76
San Martín Del Camino             75
Carrión De Los Condes             72
Mansilla De Las Mulas             55
Frómista                          54
Bercianos Del Real Camino         48
Ribadesella                       48
Oviedo                            45
Avilés                            42
Sebrayo                           39
Gijón                             38
Salas                             37
Llanes                            35
San Juan de Villapañada           33
Muros de Nalón                    32
Labruge                           29
Soto de Luiña                     29
Oporto                            15
Rabaçal                           10
Águeda                             8
Coímbra                            7
Albergaria A Velha                 6
Mealhada                           6
Grijó                              6
Oliveira de Azeméis                5
Tábara                             2
Granja de Moreruela                1
Name: 23/06/2023, dtype: int64

In [122]:
peregrinos_

,Codigo,Fechaform,Cluster,Origen,Camino,OrigenCamino,Etapa,dayofyear,llegada
Fecha,,,,,,,,,
2022-07-04,P000001,44746,2.0,Ponferrada,Frances,PonferradaFrances,9.0,185,33
2022-07-04,P000002,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000004,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000005,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
2022-07-04,P000006,44746,2.0,Sarria,Frances,SarriaFrances,5.0,185,33
...,...,...,...,...,...,...,...,...,...
2022-07-10,P012933,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012934,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012936,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012937,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39
2022-07-10,P012938,44752,0.0,Sarria,Frances,SarriaFrances,5.0,191,39

In [123]:
codigo_cluster_dict = dict(zip( peregrinos_['Codigo'], peregrinos_['Cluster']))
codigo_cluster_dict

{'P000001': 2.0,
 'P000002': 2.0,
 'P000004': 2.0,
 'P000005': 2.0,
 'P000006': 2.0,
 'P000007': 2.0,
 'P000008': 2.0,
 'P000010': 2.0,
 'P000011': 2.0,
 'P000013': 2.0,
 'P000014': 2.0,
 'P000015': 2.0,
 'P000016': 2.0,
 'P000017': 2.0,
 'P000018': 2.0,
 'P000019': 2.0,
 'P000020': 2.0,
 'P000021': 2.0,
 'P000022': 2.0,
 'P000023': 2.0,
 'P000024': 2.0,
 'P000025': 2.0,
 'P000026': 2.0,
 'P000027': 2.0,
 'P000028': 2.0,
 'P000029': 2.0,
 'P000030': 2.0,
 'P000031': 2.0,
 'P000032': 2.0,
 'P000033': 2.0,
 'P000034': 2.0,
 'P000035': 2.0,
 'P000036': 2.0,
 'P000037': 2.0,
 'P000038': 2.0,
 'P000039': 2.0,
 'P000040': 2.0,
 'P000041': 2.0,
 'P000042': 2.0,
 'P000043': 2.0,
 'P000044': 2.0,
 'P000045': 2.0,
 'P000046': 2.0,
 'P000047': 2.0,
 'P000048': 2.0,
 'P000049': 2.0,
 'P000051': 2.0,
 'P000053': 2.0,
 'P000054': 2.0,
 'P000055': 2.0,
 'P000056': 2.0,
 'P000057': 2.0,
 'P000058': 2.0,
 'P000061': 2.0,
 'P000062': 2.0,
 'P000063': 2.0,
 'P000064': 2.0,
 'P000065': 2.0,
 'P000066': 2.0,
 'P000067': 2.0,
 'P000068': 2.0,
 'P000069': 2.0,
 'P000070': 2.0,
 'P000071': 2.0,
 'P000072': 2.0,
 'P000073': 2.0,
 'P000074': 2.0,
 'P000075': 2.0,
 'P000076': 2.0,
 'P000078': 2.0,
 'P000079': 2.0,
 'P000080': 2.0,
 'P000081': 2.0,
 'P000082': 2.0,
 'P000083': 2.0,
 'P000084': 2.0,
 'P000085': 2.0,
 'P000086': 2.0,
 'P000087': 2.0,
 'P000088': 2.0,
 'P000089': 2.0,
 'P000090': 2.0,
 'P000091': 2.0,
 'P000092': 2.0,
 'P000093': 2.0,
 'P000094': 2.0,
 'P000095': 2.0,
 'P000096': 2.0,
 'P000097': 2.0,
 'P000099': 2.0,
 'P000100': 2.0,
 'P000101': 2.0,
 'P000102': 2.0,
 'P000104': 2.0,
 'P000107': 2.0,
 'P000108': 2.0,
 'P000109': 2.0,
 'P000110': 2.0,
 'P000111': 2.0,
 'P000112': 2.0,
 'P000113': 2.0,
 'P000114': 2.0,
 'P000115': 2.0,
 'P000116': 2.0,
 'P000117': 2.0,
 'P000118': 2.0,
 'P000119': 2.0,
 'P000121': 2.0,
 'P000122': 2.0,
 'P000123': 2.0,
 'P000124': 2.0,
 'P000125': 2.0,
 'P000126': 2.0,
 'P000127': 2.0,
 'P000128': 2.0,
 'P000129': 2.0,
 'P000130': 2.0,
 'P000131': 2.0,
 'P000133': 2.0,
 'P000134': 2.0,
 'P000135': 2.0,
 'P000136': 2.0,
 'P000137': 2.0,
 'P000138': 2.0,
 'P000139': 2.0,
 'P000140': 2.0,
 'P000141': 2.0,
 'P000142': 2.0,
 'P000143': 2.0,
 'P000144': 2.0,
 'P000145': 2.0,
 'P000146': 2.0,
 'P000149': 2.0,
 'P000150': 2.0,
 'P000151': 2.0,
 'P000152': 2.0,
 'P000153': 2.0,
 'P000154': 2.0,
 'P000155': 2.0,
 'P000156': 2.0,
 'P000157': 2.0,
 'P000158': 2.0,
 'P000159': 2.0,
 'P000161': 2.0,
 'P000162': 2.0,
 'P000163': 2.0,
 'P000164': 2.0,
 'P000165': 2.0,
 'P000166': 2.0,
 'P000167': 2.0,
 'P000168': 2.0,
 'P000169': 2.0,
 'P000170': 2.0,
 'P000171': 2.0,
 'P000172': 2.0,
 'P000173': 2.0,
 'P000174': 2.0,
 'P000175': 2.0,
 'P000176': 2.0,
 'P000177': 2.0,
 'P000178': 2.0,
 'P000179': 2.0,
 'P000180': 2.0,
 'P000181': 2.0,
 'P000182': 2.0,
 'P000183': 2.0,
 'P000184': 2.0,
 'P000185': 2.0,
 'P000186': 2.0,
 'P000187': 2.0,
 'P000188': 2.0,
 'P000189': 2.0,
 'P000190': 2.0,
 'P000191': 2.0,
 'P000193': 2.0,
 'P000194': 2.0,
 'P000195': 2.0,
 'P000196': 2.0,
 'P000197': 2.0,
 'P000198': 2.0,
 'P000199': 2.0,
 'P000200': 2.0,
 'P000202': 2.0,
 'P000203': 2.0,
 'P000204': 2.0,
 'P000205': 2.0,
 'P000206': 2.0,
 'P000207': 2.0,
 'P000208': 2.0,
 'P000209': 2.0,
 'P000210': 2.0,
 'P000211': 2.0,
 'P000212': 2.0,
 'P000213': 2.0,
 'P000214': 2.0,
 'P000215': 2.0,
 'P000216': 2.0,
 'P000217': 2.0,
 'P000218': 2.0,
 'P000221': 2.0,
 'P000222': 2.0,
 'P000223': 2.0,
 'P000224': 2.0,
 'P000225': 2.0,
 'P000226': 2.0,
 'P000227': 2.0,
 'P000229': 2.0,
 'P000230': 2.0,
 'P000231': 2.0,
 'P000232': 2.0,
 'P000233': 2.0,
 'P000234': 2.0,
 'P000235': 2.0,
 'P000236': 2.0,
 'P000237': 2.0,
 'P000238': 2.0,
 'P000239': 2.0,
 'P000240': 2.0,
 'P000241': 2.0,
 'P000242': 2.0,
 'P000243': 2.0,
 'P000244': 2.0,
 'P000245': 2.0,
 'P000246': 2.0,
 'P000247': 2.0,
 'P000248': 2.0,
 'P000249': 2.0,
 'P000250': 2.0,
 'P000252': 2.0,
 'P000253': 2.0,
 'P000254': 2.0,
 'P000255': 2.0,
 'P000256': 2.0,
 'P000257': 2.0,
 'P000260': 2.0,
 'P000261': 2.0,
 'P000262': 2.0,
 'P000263': 2.0,
 'P000264': 2.0,
 'P000265': 2.0,
 'P000266': 2.0,
 'P000267': 2.0,
 'P000268': 2.0,
 'P000269': 2.0,
 'P000270': 2.0,
 'P000271': 2.0,
 'P000272': 2.0,
 'P000273': 2.0,
 'P000274': 2.0,
 'P000275': 2.0,
 'P000276': 2.0,
 'P000277': 2.0,
 'P000278': 2.0,
 'P000279': 2.0,
 'P000281': 2.0,
 'P000282': 2.0,
 'P000283': 2.0,
 'P000284': 2.0,
 'P000285': 2.0,
 'P000286': 2.0,
 'P000287': 2.0,
 'P000288': 2.0,
 'P000289': 2.0,
 'P000290': 2.0,
 'P000291': 2.0,
 'P000292': 2.0,
 'P000293': 2.0,
 'P000294': 2.0,
 'P000295': 2.0,
 'P000296': 2.0,
 'P000297': 2.0,
 'P000298': 2.0,
 'P000299': 2.0,
 'P000300': 2.0,
 'P000301': 2.0,
 'P000302': 2.0,
 'P000303': 2.0,
 'P000304': 2.0,
 'P000305': 2.0,
 'P000306': 2.0,
 'P000307': 2.0,
 'P000308': 2.0,
 'P000309': 2.0,
 'P000310': 2.0,
 'P000311': 2.0,
 'P000312': 2.0,
 'P000313': 2.0,
 'P000314': 2.0,
 'P000315': 2.0,
 'P000317': 2.0,
 'P000318': 2.0,
 'P000319': 2.0,
 'P000320': 2.0,
 'P000321': 2.0,
 'P000322': 2.0,
 'P000323': 2.0,
 'P000324': 2.0,
 'P000326': 2.0,
 'P000328': 2.0,
 'P000329': 2.0,
 'P000330': 2.0,
 'P000331': 2.0,
 'P000332': 2.0,
 'P000333': 2.0,
 'P000334': 2.0,
 'P000335': 2.0,
 'P000336': 2.0,
 'P000337': 2.0,
 'P000338': 2.0,
 'P000339': 2.0,
 'P000340': 2.0,
 'P000342': 2.0,
 'P000344': 2.0,
 'P000346': 2.0,
 'P000347': 2.0,
 'P000348': 2.0,
 'P000349': 2.0,
 'P000350': 2.0,
 'P000351': 2.0,
 'P000352': 2.0,
 'P000353': 2.0,
 'P000354': 2.0,
 'P000356': 2.0,
 'P000357': 2.0,
 'P000359': 2.0,
 'P000360': 2.0,
 'P000361': 2.0,
 'P000362': 2.0,
 'P000363': 2.0,
 'P000364': 2.0,
 'P000365': 2.0,
 'P000366': 2.0,
 'P000367': 2.0,
 'P000368': 2.0,
 'P000369': 2.0,
 'P000370': 2.0,
 'P000371': 2.0,
 'P000372': 2.0,
 'P000373': 2.0,
 'P000374': 2.0,
 'P000375': 2.0,
 'P000376': 2.0,
 'P000378': 2.0,
 'P000379': 2.0,
 'P000380': 2.0,
 'P000381': 2.0,
 'P000382': 2.0,
 'P000383': 2.0,
 'P000385': 2.0,
 'P000386': 2.0,
 'P000387': 2.0,
 'P000388': 2.0,
 'P000389': 2.0,
 'P000390': 2.0,
 'P000391': 2.0,
 'P000392': 2.0,
 'P000394': 2.0,
 'P000395': 2.0,
 'P000396': 2.0,
 'P000397': 2.0,
 'P000398': 2.0,
 'P000399': 2.0,
 'P000400': 2.0,
 'P000402': 2.0,
 'P000403': 2.0,
 'P000404': 2.0,
 'P000405': 2.0,
 'P000406': 2.0,
 'P000407': 2.0,
 'P000408': 2.0,
 'P000409': 2.0,
 'P000410': 2.0,
 'P000411': 2.0,
 'P000412': 2.0,
 'P000413': 2.0,
 'P000414': 2.0,
 'P000415': 2.0,
 'P000416': 2.0,
 'P000417': 2.0,
 'P000419': 2.0,
 'P000420': 2.0,
 'P000421': 2.0,
 'P000422': 2.0,
 'P000423': 2.0,
 'P000424': 2.0,
 'P000425': 2.0,
 'P000427': 2.0,
 'P000428': 2.0,
 'P000429': 2.0,
 'P000431': 2.0,
 'P000433': 2.0,
 'P000434': 2.0,
 'P000435': 2.0,
 'P000436': 2.0,
 'P000437': 2.0,
 'P000438': 2.0,
 'P000439': 2.0,
 'P000440': 2.0,
 'P000442': 2.0,
 'P000443': 2.0,
 'P000444': 2.0,
 'P000445': 2.0,
 'P000446': 2.0,
 'P000447': 2.0,
 'P000448': 2.0,
 'P000450': 2.0,
 'P000451': 2.0,
 'P000452': 2.0,
 'P000453': 2.0,
 'P000454': 2.0,
 'P000455': 2.0,
 'P000456': 2.0,
 'P000457': 2.0,
 'P000458': 2.0,
 'P000459': 2.0,
 'P000460': 2.0,
 'P000461': 2.0,
 'P000462': 2.0,
 'P000463': 2.0,
 'P000464': 2.0,
 'P000465': 2.0,
 'P000466': 2.0,
 'P000467': 2.0,
 'P000468': 2.0,
 'P000469': 2.0,
 'P000471': 2.0,
 'P000472': 2.0,
 'P000473': 2.0,
 'P000474': 2.0,
 'P000475': 2.0,
 'P000476': 2.0,
 'P000477': 2.0,
 'P000478': 2.0,
 'P000479': 2.0,
 'P000480': 2.0,
 'P000481': 2.0,
 'P000482': 2.0,
 'P000483': 2.0,
 'P000484': 2.0,
 'P000486': 2.0,
 'P000487': 2.0,
 'P000488': 2.0,
 'P000489': 2.0,
 'P000490': 2.0,
 'P000491': 2.0,
 'P000492': 2.0,
 'P000493': 2.0,
 'P000494': 2.0,
 'P000495': 2.0,
 'P000496': 2.0,
 'P000497': 2.0,
 'P000499': 2.0,
 'P000500': 2.0,
 'P000501': 2.0,
 'P000502': 2.0,
 'P000503': 2.0,
 'P000504': 2.0,
 'P000506': 2.0,
 'P000507': 2.0,
 'P000508': 2.0,
 'P000509': 2.0,
 'P000510': 2.0,
 'P000511': 2.0,
 'P000512': 2.0,
 'P000513': 2.0,
 'P000514': 2.0,
 'P000515': 2.0,
 'P000516': 2.0,
 'P000517': 2.0,
 'P000518': 2.0,
 'P000519': 2.0,
 'P000520': 2.0,
 'P000521': 2.0,
 'P000522': 2.0,
 'P000523': 2.0,
 'P000524': 2.0,
 'P000525': 2.0,
 'P000526': 2.0,
 'P000527': 2.0,
 'P000528': 2.0,
 'P000529': 2.0,
 'P000530': 2.0,
 'P000532': 2.0,
 'P000533': 2.0,
 'P000534': 2.0,
 'P000535': 2.0,
 'P000536': 2.0,
 'P000537': 2.0,
 'P000538': 2.0,
 'P000539': 2.0,
 'P000540': 2.0,
 'P000541': 2.0,
 'P000542': 2.0,
 'P000543': 2.0,
 'P000544': 2.0,
 'P000546': 2.0,
 'P000547': 2.0,
 'P000548': 2.0,
 'P000549': 2.0,
 'P000550': 2.0,
 'P000551': 2.0,
 'P000552': 2.0,
 'P000554': 2.0,
 'P000555': 2.0,
 'P000556': 2.0,
 'P000557': 2.0,
 'P000558': 2.0,
 'P000559': 2.0,
 'P000560': 2.0,
 'P000561': 2.0,
 'P000562': 2.0,
 'P000563': 2.0,
 'P000564': 2.0,
 'P000565': 2.0,
 'P000566': 2.0,
 'P000567': 2.0,
 'P000568': 2.0,
 'P000569': 2.0,
 'P000570': 2.0,
 'P000572': 2.0,
 'P000573': 2.0,
 'P000574': 2.0,
 'P000575': 2.0,
 'P000576': 2.0,
 'P000577': 2.0,
 'P000578': 2.0,
 'P000579': 2.0,
 'P000581': 2.0,
 'P000582': 2.0,
 'P000583': 2.0,
 'P000584': 2.0,
 'P000585': 2.0,
 'P000586': 2.0,
 'P000587': 2.0,
 'P000588': 2.0,
 'P000589': 2.0,
 'P000590': 2.0,
 'P000591': 2.0,
 'P000593': 2.0,
 'P000594': 2.0,
 'P000596': 2.0,
 'P000597': 2.0,
 'P000599': 2.0,
 'P000603': 2.0,
 'P000604': 2.0,
 'P000605': 2.0,
 'P000607': 2.0,
 'P000608': 2.0,
 'P000610': 2.0,
 'P000613': 2.0,
 'P000615': 2.0,
 'P000616': 2.0,
 'P000617': 2.0,
 'P000618': 2.0,
 'P000619': 2.0,
 'P000620': 2.0,
 'P000621': 2.0,
 'P000622': 2.0,
 'P000623': 2.0,
 'P000624': 2.0,
 'P000625': 2.0,
 'P000627': 2.0,
 'P000628': 2.0,
 'P000629': 2.0,
 'P000630': 2.0,
 'P000631': 2.0,
 'P000632': 2.0,
 'P000633': 2.0,
 'P000634': 2.0,
 'P000635': 2.0,
 'P000637': 2.0,
 'P000638': 2.0,
 'P000639': 2.0,
 'P000640': 2.0,
 'P000641': 2.0,
 'P000642': 2.0,
 'P000643': 2.0,
 'P000644': 2.0,
 'P000645': 2.0,
 'P000647': 2.0,
 'P000648': 2.0,
 'P000649': 2.0,
 'P000650': 2.0,
 'P000651': 2.0,
 'P000652': 2.0,
 'P000653': 2.0,
 'P000655': 2.0,
 'P000656': 2.0,
 'P000657': 2.0,
 'P000659': 2.0,
 'P000660': 2.0,
 'P000661': 2.0,
 'P000662': 2.0,
 'P000664': 2.0,
 'P000665': 2.0,
 'P000666': 2.0,
 'P000667': 2.0,
 'P000668': 2.0,
 'P000669': 2.0,
 'P000670': 2.0,
 'P000671': 2.0,
 'P000672': 2.0,
 'P000673': 2.0,
 'P000674': 2.0,
 'P000675': 2.0,
 'P000676': 2.0,
 'P000677': 2.0,
 'P000678': 2.0,
 'P000679': 2.0,
 'P000680': 2.0,
 'P000681': 2.0,
 'P000682': 2.0,
 'P000683': 2.0,
 'P000684': 2.0,
 'P000686': 2.0,
 'P000687': 2.0,
 'P000688': 2.0,
 'P000690': 2.0,
 'P000691': 2.0,
 'P000693': 2.0,
 'P000695': 2.0,
 'P000696': 2.0,
 'P000697': 2.0,
 'P000698': 2.0,
 'P000700': 2.0,
 'P000701': 2.0,
 'P000702': 2.0,
 'P000703': 2.0,
 'P000706': 2.0,
 'P000707': 2.0,
 'P000708': 2.0,
 'P000710': 2.0,
 'P000711': 2.0,
 'P000712': 2.0,
 'P000713': 2.0,
 'P000714': 2.0,
 'P000715': 2.0,
 'P000716': 2.0,
 'P000717': 2.0,
 'P000718': 2.0,
 'P000719': 2.0,
 'P000720': 2.0,
 'P000721': 2.0,
 'P000722': 2.0,
 'P000723': 2.0,
 'P000724': 2.0,
 'P000726': 2.0,
 'P000727': 2.0,
 'P000728': 2.0,
 'P000729': 2.0,
 'P000730': 2.0,
 'P000731': 2.0,
 'P000732': 2.0,
 'P000733': 2.0,
 'P000734': 2.0,
 'P000735': 2.0,
 'P000736': 2.0,
 'P000737': 2.0,
 'P000738': 2.0,
 'P000739': 2.0,
 'P000740': 2.0,
 'P000741': 2.0,
 'P000742': 2.0,
 'P000743': 2.0,
 'P000744': 2.0,
 'P000745': 2.0,
 'P000746': 2.0,
 'P000747': 2.0,
 'P000748': 2.0,
 'P000749': 2.0,
 'P000750': 2.0,
 'P000751': 2.0,
 'P000752': 2.0,
 'P000753': 2.0,
 'P000754': 2.0,
 'P000755': 2.0,
 'P000756': 2.0,
 'P000757': 2.0,
 'P000758': 2.0,
 'P000759': 2.0,
 'P000760': 2.0,
 'P000761': 2.0,
 'P000762': 2.0,
 'P000763': 2.0,
 'P000765': 2.0,
 'P000766': 2.0,
 'P000767': 2.0,
 'P000769': 2.0,
 'P000770': 2.0,
 'P000771': 2.0,
 'P000772': 2.0,
 'P000773': 2.0,
 'P000775': 2.0,
 'P000776': 2.0,
 'P000777': 2.0,
 'P000778': 2.0,
 'P000781': 2.0,
 'P000782': 2.0,
 'P000783': 2.0,
 'P000784': 2.0,
 'P000785': 2.0,
 'P000786': 2.0,
 'P000787': 2.0,
 'P000788': 2.0,
 'P000789': 2.0,
 'P000790': 2.0,
 'P000791': 2.0,
 'P000792': 2.0,
 'P000793': 2.0,
 'P000794': 2.0,
 'P000795': 2.0,
 'P000796': 2.0,
 'P000797': 2.0,
 'P000798': 2.0,
 'P000799': 2.0,
 'P000800': 2.0,
 'P000801': 2.0,
 'P000803': 2.0,
 'P000804': 2.0,
 'P000805': 2.0,
 'P000806': 2.0,
 'P000807': 2.0,
 'P000808': 2.0,
 'P000809': 2.0,
 'P000810': 2.0,
 'P000811': 2.0,
 'P000812': 2.0,
 'P000813': 2.0,
 'P000815': 2.0,
 'P000816': 2.0,
 'P000817': 2.0,
 'P000818': 2.0,
 'P000819': 2.0,
 'P000820': 2.0,
 'P000822': 2.0,
 'P000823': 2.0,
 'P000825': 2.0,
 'P000826': 2.0,
 'P000828': 2.0,
 'P000829': 2.0,
 'P000830': 2.0,
 'P000831': 2.0,
 'P000832': 2.0,
 'P000833': 2.0,
 'P000834': 2.0,
 'P000835': 2.0,
 'P000836': 2.0,
 'P000837': 2.0,
 'P000838': 2.0,
 'P000839': 2.0,
 'P000840': 2.0,
 'P000841': 2.0,
 'P000842': 2.0,
 'P000843': 2.0,
 'P000844': 2.0,
 'P000845': 2.0,
 'P000846': 2.0,
 'P000847': 2.0,
 'P000848': 2.0,
 'P000849': 2.0,
 'P000850': 2.0,
 'P000851': 2.0,
 'P000852': 2.0,
 'P000853': 2.0,
 'P000854': 2.0,
 'P000855': 2.0,
 'P000857': 2.0,
 'P000858': 2.0,
 'P000859': 2.0,
 'P000860': 2.0,
 'P000861': 2.0,
 'P000862': 2.0,
 'P000863': 2.0,
 'P000864': 2.0,
 'P000865': 2.0,
 'P000866': 2.0,
 'P000867': 2.0,
 'P000868': 2.0,
 'P000869': 2.0,
 'P000870': 2.0,
 'P000871': 2.0,
 'P000872': 2.0,
 'P000873': 2.0,
 'P000875': 2.0,
 'P000876': 2.0,
 'P000877': 2.0,
 'P000878': 2.0,
 'P000879': 2.0,
 'P000880': 2.0,
 'P000881': 2.0,
 'P000882': 2.0,
 'P000883': 2.0,
 'P000884': 2.0,
 'P000885': 2.0,
 'P000886': 2.0,
 'P000887': 2.0,
 'P000888': 2.0,
 'P000889': 2.0,
 'P000890': 2.0,
 'P000891': 2.0,
 'P000892': 2.0,
 'P000893': 2.0,
 'P000895': 2.0,
 'P000896': 2.0,
 'P000897': 2.0,
 'P000898': 2.0,
 'P000899': 2.0,
 'P000902': 2.0,
 'P000903': 2.0,
 'P000904': 2.0,
 'P000905': 2.0,
 'P000906': 2.0,
 'P000907': 2.0,
 'P000908': 2.0,
 'P000909': 2.0,
 'P000910': 2.0,
 'P000911': 2.0,
 'P000912': 2.0,
 'P000914': 2.0,
 'P000915': 2.0,
 'P000917': 2.0,
 'P000918': 2.0,
 'P000920': 2.0,
 'P000921': 2.0,
 'P000922': 2.0,
 'P000923': 2.0,
 'P000924': 2.0,
 'P000925': 2.0,
 'P000926': 2.0,
 'P000927': 2.0,
 'P000928': 2.0,
 'P000929': 2.0,
 'P000930': 2.0,
 'P000931': 2.0,
 'P000932': 2.0,
 'P000933': 2.0,
 'P000934': 2.0,
 'P000936': 2.0,
 'P000937': 2.0,
 'P000938': 2.0,
 'P000939': 2.0,
 'P000940': 2.0,
 'P000942': 2.0,
 'P000943': 2.0,
 'P000944': 2.0,
 'P000945': 2.0,
 'P000946': 2.0,
 'P000947': 2.0,
 'P000948': 2.0,
 'P000950': 2.0,
 'P000951': 2.0,
 'P000952': 2.0,
 'P000953': 2.0,
 'P000954': 2.0,
 'P000955': 2.0,
 'P000956': 2.0,
 'P000957': 2.0,
 'P000958': 2.0,
 'P000959': 2.0,
 'P000960': 2.0,
 'P000961': 2.0,
 'P000962': 2.0,
 'P000963': 2.0,
 'P000964': 2.0,
 'P000965': 2.0,
 'P000966': 2.0,
 'P000967': 2.0,
 'P000968': 2.0,
 'P000969': 2.0,
 'P000970': 2.0,
 'P000971': 2.0,
 'P000972': 2.0,
 'P000973': 2.0,
 'P000974': 2.0,
 'P000975': 2.0,
 'P000977': 2.0,
 'P000978': 2.0,
 'P000979': 2.0,
 'P000980': 2.0,
 'P000981': 2.0,
 'P000982': 2.0,
 'P000983': 2.0,
 'P000984': 2.0,
 'P000985': 2.0,
 'P000987': 2.0,
 'P000988': 2.0,
 'P000989': 2.0,
 'P000990': 2.0,
 'P000991': 2.0,
 'P000992': 2.0,
 'P000993': 2.0,
 'P000994': 2.0,
 'P000995': 2.0,
 'P000996': 2.0,
 'P000997': 2.0,
 'P000998': 2.0,
 'P000999': 2.0,
 'P001000': 2.0,
 'P001001': 2.0,
 'P001002': 2.0,
 'P001003': 2.0,
 'P001004': 2.0,
 'P001005': 2.0,
 'P001006': 2.0,
 'P001007': 2.0,
 'P001008': 2.0,
 'P001009': 2.0,
 'P001010': 2.0,
 'P001011': 2.0,
 'P001012': 2.0,
 'P001013': 2.0,
 'P001014': 2.0,
 'P001015': 2.0,
 'P001016': 2.0,
 'P001017': 2.0,
 'P001018': 2.0,
 'P001019': 2.0,
 'P001020': 2.0,
 'P001021': 2.0,
 'P001022': 2.0,
 'P001023': 2.0,
 'P001024': 2.0,
 'P001025': 2.0,
 'P001026': 2.0,
 'P001027': 2.0,
 'P001028': 2.0,
 'P001029': 2.0,
 'P001030': 2.0,
 'P001031': 2.0,
 'P001032': 2.0,
 'P001033': 2.0,
 'P001034': 2.0,
 'P001036': 2.0,
 'P001037': 2.0,
 'P001038': 2.0,
 'P001039': 2.0,
 'P001041': 2.0,
 'P001042': 2.0,
 'P001043': 2.0,
 'P001044': 2.0,
 'P001046': 2.0,
 'P001047': 2.0,
 'P001048': 2.0,
 'P001049': 2.0,
 'P001050': 2.0,
 'P001051': 2.0,
 'P001052': 2.0,
 'P001053': 2.0,
 'P001054': 2.0,
 'P001055': 2.0,
 'P001056': 2.0,
 'P001057': 2.0,
 'P001058': 2.0,
 'P001059': 2.0,
 'P001061': 2.0,
 'P001062': 2.0,
 'P001063': 2.0,
 'P001064': 2.0,
 'P001065': 2.0,
 'P001066': 2.0,
 'P001068': 2.0,
 'P001069': 2.0,
 'P001071': 2.0,
 'P001072': 2.0,
 'P001075': 2.0,
 'P001076': 2.0,
 'P001077': 2.0,
 'P001078': 2.0,
 'P001079': 2.0,
 'P001080': 2.0,
 'P001081': 2.0,
 'P001082': 2.0,
 'P001083': 2.0,
 'P001084': 2.0,
 'P001085': 2.0,
 'P001087': 2.0,
 'P001089': 2.0,
 'P001090': 2.0,
 'P001091': 2.0,
 'P001092': 2.0,
 'P001093': 2.0,
 'P001094': 2.0,
 'P001095': 2.0,
 'P001096': 2.0,
 'P001097': 2.0,
 'P001098': 2.0,
 'P001099': 2.0,
 'P001100': 2.0,
 'P001101': 2.0,
 'P001102': 2.0,
 'P001103': 2.0,
 'P001104': 2.0,
 'P001105': 2.0,
 'P001106': 2.0,
 'P001107': 2.0,
 'P001109': 2.0,
 'P001110': 2.0,
 'P001111': 2.0,
 'P001112': 2.0,
 'P001114': 2.0,
 ...}

In [136]:
df_itinerario_sorted[df_itinerario_sorted['04/07/2023'] == 'Santiago de Compostela'].Cluster.value_counts()

1.0    482
2.0    376
0.0    367
Name: Cluster, dtype: int64

In [169]:
df_itinerario_sorted.to_csv('itinererio_powerbi_final.csv')

In [174]:


df_temporal = pd.DataFrame()


for fecha_columna in df_itinerario_sorted.columns:
    i = 0 
    ciudad_unica = df_itinerario_sorted[df_itinerario_sorted[fecha_columna].notna()][fecha_columna].unique()
    frecuencias = df_itinerario_sorted[fecha_columna].value_counts()
    
 
    for ciudad in ciudad_unica:
        
        df_temporal.loc[fecha_columna,ciudad] = frecuencias[ciudad]

In [175]:
df_temporal.to_csv('itinererio_corregido_final.csv')

In [176]:
import random

In [177]:
df_temporal

,Irún,Saint Jean Pied de Port,San Sebastián,Roncesvalles,Zarautz,Zubiri,Deba,Pamplona,Markina,Puente la Reina,...,Melide,Arzúa,Caldas de Reis,A Laxe,Bruma,Caldas de Reis,Santiago de Compostela,2.0,1.0,0.0
152,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/06/2023,17.0,22.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,21.0,28.0,18.0,22.0,18.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,22.0,31.0,22.0,28.0,18.0,22.0,18.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,19.0,26.0,24.0,31.0,22.0,28.0,18.0,26.0,18.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/06/2023,24.0,48.0,22.0,26.0,24.0,31.0,22.0,34.0,18.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
07/06/2023,25.0,40.0,27.0,48.0,22.0,26.0,24.0,40.0,22.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
08/06/2023,NaN,32.0,28.0,40.0,27.0,48.0,22.0,32.0,24.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09/06/2023,NaN,NaN,NaN,32.0,28.0,40.0,27.0,53.0,22.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/06/2023,NaN,NaN,NaN,NaN,NaN,32.0,28.0,48.0,27.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,28.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.0,821.0,227.0,57.0,82.0,38.0,NaN,NaN,NaN,NaN
04/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82.0,861.0,227.0,57.0,122.0,25.0,1225.0,NaN,NaN,NaN
05/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.0,972.0,270.0,90.0,116.0,46.0,1292.0,NaN,NaN,NaN
06/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.0,1156.0,305.0,75.0,156.0,44.0,1494.0,NaN,NaN,NaN
07/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.0,1269.0,347.0,96.0,158.0,61.0,1736.0,NaN,NaN,NaN
08/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.0,1157.0,312.0,102.0,154.0,50.0,1931.0,NaN,NaN,NaN
09/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1165.0,305.0,88.0,158.0,47.0,1775.0,NaN,NaN,NaN
10/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1763.0,NaN,NaN,NaN
Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3330.0,4431.0,3455.0

In [183]:
df_itinerario_sorted_c2 = df_itinerario_sorted[df_itinerario_sorted['Cluster']==2]
df_itinerario_sorted_c1 = df_itinerario_sorted[df_itinerario_sorted['Cluster']==1]
df_itinerario_sorted_c0 = df_itinerario_sorted[df_itinerario_sorted['Cluster']==0]

In [180]:
df_itinerario_sorted_c2

,152,02/06/2023,03/06/2023,04/06/2023,05/06/2023,06/06/2023,07/06/2023,08/06/2023,09/06/2023,10/06/2023,...,02/07/2023,03/07/2023,04/07/2023,05/07/2023,06/07/2023,07/07/2023,08/07/2023,09/07/2023,10/07/2023,Cluster
Peregrino,,,,,,,,,,,,,,,,,,,,,
P000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN,2.0
P000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN,2.0
P000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN,2.0
P000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN,2.0
P000006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Palas de Rei,Arzúa,Santiago de Compostela,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P003684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
P003686,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,O Cebreiro,Triacastela,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
P003687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
P003688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
P003689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ponferrada,Villafranca Del Bierzo,O Cebreiro,Triacastela,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0

In [181]:

df_temporal2 = pd.DataFrame()


for fecha_columna in df_itinerario_sorted_c2.columns:
    i = 0 
    ciudad_unica = df_itinerario_sorted_c2[df_itinerario_sorted_c2[fecha_columna].notna()][fecha_columna].unique()
    frecuencias = df_itinerario_sorted_c2[fecha_columna].value_counts()
    
 
    for ciudad in ciudad_unica:
        
        df_temporal2.loc[fecha_columna,ciudad] = frecuencias[ciudad]

In [182]:
df_temporal2

,Saint Jean Pied de Port,Roncesvalles,Zubiri,Pamplona,Puente la Reina,Estella,Los Arcos,Logroño,Nájera,Santo Domingo de La Calzada,...,Ponferrada,Villafranca Del Bierzo,O Cebreiro,Triacastela,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
02/06/2023,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,19.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,19.0,19.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,17.0,19.0,19.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/06/2023,28.0,17.0,19.0,22.0,14.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
07/06/2023,21.0,28.0,17.0,23.0,22.0,14.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
08/06/2023,16.0,21.0,28.0,18.0,23.0,22.0,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09/06/2023,NaN,16.0,21.0,31.0,18.0,23.0,22.0,16.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/06/2023,NaN,NaN,16.0,25.0,31.0,18.0,23.0,25.0,16.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11/06/2023,NaN,NaN,NaN,19.0,27.0,31.0,18.0,26.0,25.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12/06/2023,NaN,NaN,NaN,NaN,19.0,27.0,31.0,20.0,26.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13/06/2023,NaN,NaN,NaN,NaN,NaN,19.0,27.0,34.0,20.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,19.0,28.0,34.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,28.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.0,96.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.0,97.0,136.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,135.0,111.0,138.0,145.0,NaN,NaN,NaN,NaN,NaN,NaN
30/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,155.0,138.0,157.0,147.0,376.0,NaN,NaN,NaN,NaN,NaN
01/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,123.0,162.0,201.0,168.0,350.0,376.0,NaN,NaN,NaN,NaN
02/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,115.0,130.0,222.0,209.0,455.0,350.0,376.0,NaN,NaN,NaN
03/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,119.0,212.0,239.0,495.0,455.0,350.0,376.0,NaN,NaN
04/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,172.0,225.0,597.0,495.0,455.0,350.0,376.0,NaN
05/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,191.0,537.0,597.0,495.0,455.0,350.0,NaN
06/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,520.0,537.0,597.0,495.0,455.0,NaN
07/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,520.0,537.0,597.0,495.0,NaN
08/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,520.0,537.0,597.0,NaN
09/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520.0,537.0,NaN
10/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520.0,NaN
Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3330.0

In [184]:

df_temporal1 = pd.DataFrame()


for fecha_columna in df_itinerario_sorted_c1.columns:
    i = 0 
    ciudad_unica = df_itinerario_sorted_c1[df_itinerario_sorted_c1[fecha_columna].notna()][fecha_columna].unique()
    frecuencias = df_itinerario_sorted_c1[fecha_columna].value_counts()
    
 
    for ciudad in ciudad_unica:
        
        df_temporal1.loc[fecha_columna,ciudad] = frecuencias[ciudad]

In [185]:

df_temporal0 = pd.DataFrame()


for fecha_columna in df_itinerario_sorted_c0.columns:
    i = 0 
    ciudad_unica = df_itinerario_sorted_c0[df_itinerario_sorted_c0[fecha_columna].notna()][fecha_columna].unique()
    frecuencias = df_itinerario_sorted_c0[fecha_columna].value_counts()
    
 
    for ciudad in ciudad_unica:
        
        df_temporal0.loc[fecha_columna,ciudad] = frecuencias[ciudad]

In [196]:
df_temporal0['Cluster'] = 0
df_temporal0 = df_temporal0.reset_index()

df_temporal0 = df_temporal0.set_index(['index', 'Cluster'])
df_temporal0.head(5)

,,level_0,Irún,San Sebastián,Saint Jean Pied de Port,Zarautz,Roncesvalles,Deba,Zubiri,Markina,Pamplona,...,Pontevedra,Cea,Betanzos,Arzúa,Caldas de Reis,A Laxe,Bruma,Santiago de Compostela,0.0,0.0
index,Cluster,,,,,,,,,,,,,,,,,,,,,
152,0,0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
02/06/2023,0,1,7.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
03/06/2023,0,2,8.0,7.0,9.0,7.0,9.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
04/06/2023,0,3,7.0,9.0,12.0,7.0,9.0,7.0,9.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
05/06/2023,0,4,9.0,7.0,9.0,9.0,12.0,7.0,9.0,7.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [197]:
df_temporal1['Cluster'] = 1
df_temporal1 = df_temporal1.reset_index()

df_temporal1 = df_temporal1.set_index(['index', 'Cluster'])
df_temporal1.head(5)

,,Irún,San Sebastián,Zarautz,Deba,Markina,Gernika Lumo,Lezama,Bilbao,Portugalete,Lisboa,...,Caldas de Reis,Arzúa,A Laxe,Bruma,Caldas de Reis,Santiago de Compostela,Sarria,Portomarín,Palas de Rei,1.0
index,Cluster,,,,,,,,,,,,,,,,,,,,,
152,1,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/06/2023,1,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,1,13.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,1,15.0,13.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,1,10.0,17.0,13.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [198]:
df_temporal2['Cluster'] = 2
df_temporal2 = df_temporal2.reset_index()

df_temporal2 = df_temporal2.set_index(['index', 'Cluster'])
df_temporal2.head(5)

,,Saint Jean Pied de Port,Roncesvalles,Zubiri,Pamplona,Puente la Reina,Estella,Los Arcos,Logroño,Nájera,Santo Domingo de La Calzada,...,Ponferrada,Villafranca Del Bierzo,O Cebreiro,Triacastela,Sarria,Portomarín,Palas de Rei,Arzúa,Santiago de Compostela,2.0
index,Cluster,,,,,,,,,,,,,,,,,,,,,
02/06/2023,2,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,2,19.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,2,19.0,19.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,2,17.0,19.0,19.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/06/2023,2,28.0,17.0,19.0,22.0,14.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [209]:
df_temporal_concat = pd.concat([df_temporal0,df_temporal1,df_temporal2])

In [210]:
df_temporal_concat.loc['152']

,level_0,Irún,San Sebastián,Saint Jean Pied de Port,Zarautz,Roncesvalles,Deba,Zubiri,Markina,Pamplona,...,Vilarinho,Marinhas,Barcelos,Ponte de Lima,Rubiães,Tui,O Porriño,Caldas de Reis,1.0,2.0
Cluster,,,,,,,,,,,,,,,,,,,,,
0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [211]:
df_temporal_concat

,,level_0,Irún,San Sebastián,Saint Jean Pied de Port,Zarautz,Roncesvalles,Deba,Zubiri,Markina,Pamplona,...,Vilarinho,Marinhas,Barcelos,Ponte de Lima,Rubiães,Tui,O Porriño,Caldas de Reis,1.0,2.0
index,Cluster,,,,,,,,,,,,,,,,,,,,,
152,0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/06/2023,0,1.0,7.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,0,2.0,8.0,7.0,9.0,7.0,9.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,0,3.0,7.0,9.0,12.0,7.0,9.0,7.0,9.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,0,4.0,9.0,7.0,9.0,9.0,12.0,7.0,9.0,7.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
07/07/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
08/07/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09/07/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/07/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cluster,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3330.0

In [214]:
df_temporal_concat.to_csv('itinerario_desglosado_cluster.csv')

In [213]:
df_temporal

,Irún,Saint Jean Pied de Port,San Sebastián,Roncesvalles,Zarautz,Zubiri,Deba,Pamplona,Markina,Puente la Reina,...,Melide,Arzúa,Caldas de Reis,A Laxe,Bruma,Caldas de Reis,Santiago de Compostela,2.0,1.0,0.0
152,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/06/2023,17.0,22.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/06/2023,21.0,28.0,18.0,22.0,18.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
04/06/2023,22.0,31.0,22.0,28.0,18.0,22.0,18.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
05/06/2023,19.0,26.0,24.0,31.0,22.0,28.0,18.0,26.0,18.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/06/2023,24.0,48.0,22.0,26.0,24.0,31.0,22.0,34.0,18.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
07/06/2023,25.0,40.0,27.0,48.0,22.0,26.0,24.0,40.0,22.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
08/06/2023,NaN,32.0,28.0,40.0,27.0,48.0,22.0,32.0,24.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
09/06/2023,NaN,NaN,NaN,32.0,28.0,40.0,27.0,53.0,22.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/06/2023,NaN,NaN,NaN,NaN,NaN,32.0,28.0,48.0,27.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,28.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30/06/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
02/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
03/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.0,821.0,227.0,57.0,82.0,38.0,NaN,NaN,NaN,NaN
04/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82.0,861.0,227.0,57.0,122.0,25.0,1225.0,NaN,NaN,NaN
05/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.0,972.0,270.0,90.0,116.0,46.0,1292.0,NaN,NaN,NaN
06/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.0,1156.0,305.0,75.0,156.0,44.0,1494.0,NaN,NaN,NaN
07/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.0,1269.0,347.0,96.0,158.0,61.0,1736.0,NaN,NaN,NaN
08/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.0,1157.0,312.0,102.0,154.0,50.0,1931.0,NaN,NaN,NaN
09/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1165.0,305.0,88.0,158.0,47.0,1775.0,NaN,NaN,NaN
10/07/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1763.0,NaN,NaN,NaN
Cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3330.0,4431.0,3455.0

In [ ]:
df_temporal_join = pd.concat([df_temporal0,df_temporal1,df_temporal2], axis=1)